<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <script>
      /*
             支持链式调用
             new Promise((resolve, reject) => {
                resolve(123)
              }).then(res => {
                console.log('success'+res);
                return 123
              }).then(res => {
                console.log('success'+res);
              }).catch(err => {
                console.log('fail'+err);
              })
          */

           /* 
          resolvePromise函数即为根据x的值来决定promise2的状态的函数
          也即标准中的[Promise Resolution Procedure](https://promisesaplus.com/#point-47)
          x为`promise2 = promise1.then(onResolved, onRejected)`里`onResolved/onRejected`的返回值
          `resolve`和`reject`实际上是`promise2`的`runFn`的两个实参，因为很难挂在其它的地方，所以一并传进来。
        */
      function resolvePromise(promise2, x, resolve, reject) {
        let then;
        var thenCalledOrThrow = false;
        if (promise2 === x) {
          //如果返回结果和
          return reject(new TypeError("Chaining cycle detected for promise!"));
        }

        if (x instanceof P) {
          // 对应标准2.3.2节
          // 如果x的状态还没有确定，那么它是有可能被一个thenable决定最终状态和值的
          // 所以这里需要做一下处理，而不能一概的以为它会被一个“正常”的值resolve
          if (x.status === "pending") {
            x.then(function(value) {
              resolvePromise(promise2, value, resolve, reject);
            }, reject);
          } else {
            // 但如果这个Promise的状态已经确定了，那么它肯定有一个“正常”的值，而不是一个thenable，所以这里直接取它的状态
            x.then(resolve, reject);
          }
          return;
        }

        if (x !== null && (typeof x === "object" || typeof x === "function")) {
          // 2.3.3
          try {
            // 2.3.3.1 因为x.then有可能是一个getter，这种情况下多次读取就有可能产生副作用
            // 即要判断它的类型，又要调用它，这就是两次读取
            then = x.then;
            if (typeof then === "function") {
              // 2.3.3.3
              then.call(
                x,
                function rs(y) {
                  // 2.3.3.3.1
                  if (thenCalledOrThrow) return; // 2.3.3.3.3 即这三处谁选执行就以谁的结果为准
                  thenCalledOrThrow = true;
                  return resolvePromise(promise2, y, resolve, reject); // 2.3.3.3.1
                },
                function rj(r) {
                  // 2.3.3.3.2
                  if (thenCalledOrThrow) return; // 2.3.3.3.3 即这三处谁选执行就以谁的结果为准
                  thenCalledOrThrow = true;
                  return reject(r);
                }
              );
            } else {
              // 2.3.3.4
              resolve(x);
            }
          } catch (e) {
            // 2.3.3.2
            if (thenCalledOrThrow) return; // 2.3.3.3.3 即这三处谁选执行就以谁的结果为准
            thenCalledOrThrow = true;
            return reject(e);
          }
        } else {
          // 2.3.4
          resolve(x);
        }
      }

      class P {
        constructor(runFn) {
          this.status = "pending"; //声明默认状态
          this.value; //声明一个闭包变量

          this.onResolvedCallbacks = [];
          this.onRejectedCallbacks = [];
          let resolve = res => {
            //执行函数体更改状态的实参  --- 更改内部的状态  接收执行更改状态传入的实参
            if (this.status === "pending") {
              //状态只能更改一次  默认状态才能更改
              this.status = "fulfilled";
              this.value = res;
              this.onResolvedCallbacks.forEach(cb => cb());
            }
          };
          let reject = rej => {
            if (this.status === "pending") {
              this.status = "rejected";
              this.value = rej;
              this.onRejectedCallbacks.forEach(cb => cb());
            }
          };

          try {
            //优化 函数体执行报错的情况应该时直接 reject
            runFn(resolve, reject); //执行函数体  传入两个更改状态的参数
          } catch (error) {
            reject.bind(this)(error);
          }
        }

        then(resolveFn, rejectFn) {
          //promise().then(fn1, fn2)接收的两个回调
          let _promise;
          // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理  如这种情况:  then(null, err => {})
          resolveFn = typeof resolveFn === "function" ? resolveFn : function(v) {};
          rejectFn = typeof rejectFn === "function" ? rejectFn : function(r) {};

          switch (
            this.status //判断状态执行不同回调
          ) {
            case "fulfilled":
              //支持链式调用 所以需要返回一个promise
              return (_promise = new P((resolve, reject) => {
                try {
                  var x = resolveFn(this.value); // 将执行函数体 更改状态值时的形参作为实参传入回调
                  resolvePromise(_promise, x, resolve, reject);
                } catch (e) {
                  reject(e); // 如果出错，以捕获到的错误做为promise2的结果
                }
              }));

              break;
            case "rejected":
              return (_promise = new P((resolve, reject) => {
                try {
                  var x = rejectFn(this.value); // 将执行函数体 更改状态值时的形参作为实参传入回调
                  resolvePromise(_promise, x, resolve, reject);
                } catch (e) {
                  reject(e); // 如果出错，以捕获到的错误做为promise2的结果
                }
              }));
              break;

            default:
              // 如果当前的Promise还处于pending状态，我们并不能确定调用onResolved还是onRejected，
              // 只能等到Promise的状态确定后，才能确实如何处理。
              // 所以我们需要把我们的**两种情况**的处理逻辑做为callback放入promise1(此处即this/self)的回调数组里
              // 逻辑本身跟第一个if块内的几乎一致，此处不做过多解释
              return (_promise = new P((resolve, reject) => {
                this.onResolvedCallbacks.push(() => {
                  try {
                    var x = resolveFn(this.value);
                    resolvePromise(_promise, x, resolve, reject);
                  } catch (e) {
                    reject(e);
                  }
                });
                this.onRejectedCallbacks.push(() => {
                  try {
                    var x = rejectFn(this.value);
                    resolvePromise(_promise, x, resolve, reject);
                  } catch (e) {
                    reject(e);
                  }
                });
              }));

              break;
          }
        }

        catch(rejectFn) {
          //实现一个catch
          return this.then(null, rejectFn);
        }
      }

      //先执行then方法是将回调添加到promise的队列任务中  之后执行更改状态的方法会遍历队列执行任务
      new P((resolve, reject) => {
        setTimeout(() => {
          reject(1234);
        }, 1000);
      })
        .then(
          res => {
            console.log(res);
            // return 2222;
            // return new P();
          }
        )
        .then(
          res => {
            console.log("2t:" + res);
            // throw error("ssss");
          }
        )
        .catch(err => {
          console.log("warn:" + err);
        });
    </script>
  </body>
</html>
