<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <script>
      /*
             支持链式调用
             new Promise((resolve, reject) => {
                resolve(123)
              }).then(res => {
                console.log('success'+res);
                return 123
              }).then(res => {
                console.log('success'+res);
              }).catch(err => {
                console.log('fail'+err);
              })
          */

      class P {
        constructor(runFn) {
          this.status = "pending"; //声明默认状态
          this.value; //声明一个闭包变量

          this.onResolvedCallbacks = [];
          this.onRejectedCallbacks = [];
          let resolve = res => {
            //执行函数体更改状态的实参  --- 更改内部的状态  接收执行更改状态传入的实参
            if (this.status === "pending") {
              //状态只能更改一次  默认状态才能更改
              this.status = "fulfilled";
              this.value = res;
              this.onResolvedCallbacks.forEach(cb => cb());
            }
          };
          let reject = rej => {
            if (this.status === "pending") {
              this.status = "rejected";
              this.value = rej;
              this.onRejectedCallbacks.forEach(cb => cb());
            }
          };

          try {
            //优化 函数体执行报错的情况应该时直接 reject
            runFn(resolve, reject); //执行函数体  传入两个更改状态的参数
          } catch (error) {
            reject.bind(this)(error);
          }
        }
        then(resolveFn, rejectFn) {
          //promise().then(fn1, fn2)接收的两个回调
          let _promise, self = this;
          // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理  如这种情况:  then(null, err => {})
          resolveFn =
            typeof resolveFn === "function" ? resolveFn : function(v) {};
          rejectFn = typeof rejectFn === "function" ? rejectFn : function(r) {};

          if (self.status == "fulfilled") {
            //支持链式调用 所以需要返回一个promise
            return (_promise = new P((resolve, reject) => {
              try {
                var x = resolveFn(self.value); // 将执行函数体 更改状态值时的形参作为实参传入回调
                if (x instanceof P) {
                  // 如果resolveFn的返回值是一个Promise对象，直接取它的结果做为promise2的结果 即： 函数体内代码 return new P...
                  console.log(9999);

                  x.then(resolve, reject);
                }
                resolve(x); // 否则，以它的返回值做为promise2的结果
              } catch (e) {
                reject(e); // 如果出错，以捕获到的错误做为promise2的结果
              }
            }));
          } else if(self.status === "rejected") {
            return (_promise = new P((resolve, reject) => {
              try {
                var x = rejectFn(self.value); // 将执行函数体 更改状态值时的形参作为实参传入回调
                if (x instanceof P) {
                  // 如果resolveFn的返回值是一个Promise对象，直接取它的结果做为promise2的结果 即： 函数体内代码 return new P...
                  x.then(resolve, reject);
                }
                
              } catch (e) {
                reject(e); // 如果出错，以捕获到的错误做为promise2的结果
              }
            }));
          } else {
            // 如果当前的Promise还处于pending状态，我们并不能确定调用onResolved还是onRejected，
              // 只能等到Promise的状态确定后，才能确实如何处理。
              // 所以我们需要把我们的**两种情况**的处理逻辑做为callback放入promise1(此处即self/self)的回调数组里
              // 逻辑本身跟第一个if块内的几乎一致，此处不做过多解释
            return (_promise = new P((resolve, reject) => {
              self.onResolvedCallbacks.push(() => {
                try {
                  var x = resolveFn(self.value);
                  if (x instanceof P) {
                    x.then(resolve, reject);
                  }
                  resolve(x);
                } catch (e) {
                  reject(e);
                }
              });
              self.onRejectedCallbacks.push(() => {
                try {
                  var x = rejectFn(self.value);
                  if (x instanceof P) {
                    x.then(resolve, reject);
                  }
                } catch (e) {
                  reject(e);
                }
              });
            }));
          }
        }

        catch(rejectFn) {
          //实现一个catch
          return this.then(null, rejectFn);
        }
      }

      //先执行then方法是将回调添加到promise的队列任务中  之后执行更改状态的方法会遍历队列执行任务
      new P((resolve, reject) => {
        // setTimeout(() => {
          reject(1234);
        // }, 1000);
      })
        .then(
          res => {
            console.log(res);
          }
        )
        .then(
          res => {
            console.log("2t:" + res);
          }
        )
        .catch(err => {
          console.log("warn:" + err);
        });
    </script>
  </body>
</html>
